'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAuth } from '@/lib/store/authStore';
import { usePosts, type Post } from '@/lib/store/postStore';
import { Button } from '@/components/ui/Button';
import { Loader2, Calendar, ArrowLeft, Trash2, Edit, Sparkles, Volume2, VolumeX } from 'lucide-react';
import Link from 'next/link';
import { motion } from 'framer-motion';

export default function PostDetailPage({ params }: { params: { id: string } }) {
    const { user } = useAuth();
    const { posts, currentPost, fetchPostById, deletePost, isLoading, error } = usePosts();
    const router = useRouter();
    const searchParams = useSearchParams();
    const [aiContent, setAiContent] = useState<string | null>(null);
    const [aiGenerating, setAiGenerating] = useState(false);
    const aiTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
    const [isSpeaking, setIsSpeaking] = useState(false);
    const [speechSupported, setSpeechSupported] = useState(false);
    const synthRef = useRef<SpeechSynthesis | null>(null);
    const utteranceRef = useRef<SpeechSynthesisUtterance | null>(null);

    const queryMeta = useMemo(() => {
        const title = searchParams.get('title') ?? undefined;
        const category = searchParams.get('category') ?? undefined;
        const excerpt = searchParams.get('excerpt') ?? undefined;
        return { title, category, excerpt };
    }, [searchParams]);

    useEffect(() => {
        fetchPostById(params.id);
    }, [params.id, fetchPostById]);

    useEffect(() => {
        return () => {
            if (aiTimerRef.current) {
                clearTimeout(aiTimerRef.current);
            }
        };
    }, []);

    const fallbackShell: Post = useMemo(
        () => ({
            id: params.id,
            title: queryMeta.title ?? 'AI Crafted Story',
            category: queryMeta.category ?? 'Insights',
            excerpt: queryMeta.excerpt ?? 'A thoughtful piece curated by Vynspire AI.',
            author: 'Vynspire AI',
            date: new Date().toISOString().split('T')[0],
            content: '',
        }),
        [params.id, queryMeta]
    );

    const basePost = currentPost ?? posts.find((p) => p.id === params.id) ?? (queryMeta.title ? fallbackShell : null);
    const effectivePost = basePost ?? (aiContent ? fallbackShell : null);
    const resolvedContent = basePost?.content?.trim() ? basePost.content : aiContent;

    const generateDraft = (meta: Post) => {
        const headline = meta.title || 'Fresh perspective';
        const category = meta.category || 'Insights';
        const intro = meta.excerpt || 'Vynspire AI distilled this topic into a concise narrative.';

        return [
            `## ${headline}`,
            '',
            `*Category: ${category} • Generated by Vynspire AI*`,
            '',
            intro,
            '',
            `1. **Setting the stage** – Where is ${category.toLowerCase()} right now and what tension exists?`,
            `2. **Signals to watch** – Detail emerging trends, data points, or anecdotes that validate the story.`,
            `3. **Takeaway** – Close each section with a question or challenge for the reader.`,
            '',
            `> Good stories blend expertise with empathy. Highlight the people, not just the products.`,
            '',
            `Wrap by summarizing why "${headline}" matters today and offer a next step readers can act on.`,
        ].join('\n');
    };

    const runAIGeneration = (meta: Post) => {
        if (aiTimerRef.current) {
            clearTimeout(aiTimerRef.current);
        }
        setAiGenerating(true);
        aiTimerRef.current = setTimeout(() => {
            setAiContent(generateDraft(meta));
            setAiGenerating(false);
            aiTimerRef.current = null;
        }, 900);
    };

    useEffect(() => {
        if (!isLoading && basePost && !basePost.content && !aiContent) {
            runAIGeneration(basePost);
        }
    }, [basePost, isLoading, aiContent]);

    useEffect(() => {
        if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
            synthRef.current = window.speechSynthesis;
            setSpeechSupported(true);
        }
        return () => {
            if (synthRef.current) {
                synthRef.current.cancel();
            }
        };
    }, []);

    useEffect(() => {
        if (isSpeaking) {
            synthRef.current?.cancel();
            setIsSpeaking(false);
        }
    }, [resolvedContent]);

    const handleDelete = async () => {
        if (confirm('Are you sure you want to delete this post?')) {
            await deletePost(params.id);
            router.push('/');
        }
    };

    const handleGenerateManually = () => {
        runAIGeneration(basePost ?? fallbackShell);
    };

    const stopSpeech = () => {
        synthRef.current?.cancel();
        utteranceRef.current = null;
        setIsSpeaking(false);
    };

    const handleToggleListen = () => {
        if (!speechSupported || !resolvedContent) return;
        if (isSpeaking) {
            stopSpeech();
            return;
        }

        const utterance = new SpeechSynthesisUtterance(`${effectivePost?.title ?? ''}. ${resolvedContent}`);
        utterance.onend = () => setIsSpeaking(false);
        utterance.onerror = () => setIsSpeaking(false);
        utteranceRef.current = utterance;
        synthRef.current?.cancel();
        synthRef.current?.speak(utterance);
        setIsSpeaking(true);
    };

    if (isLoading && !effectivePost && !aiContent) {
        return (
            <div className="flex justify-center items-center min-h-[400px]">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
        );
    }

    if (!effectivePost) {
        return (
            <div className="max-w-3xl mx-auto py-20 space-y-6 text-center">
                <p className="text-2xl font-semibold text-foreground">We couldn't find that story.</p>
                {error && <p className="text-muted-foreground text-sm">{error}</p>}
                <div className="flex justify-center">
                    <Button onClick={handleGenerateManually} isLoading={aiGenerating} className="gap-2">
                        <Sparkles size={16} />
                        Generate AI version
                    </Button>
                </div>
            </div>
        );
    }

    return (
        <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="max-w-4xl mx-auto pb-20"
        >
            <Link href="/">
                <Button variant="ghost" className="mb-6 pl-0 hover:pl-2 transition-all text-muted-foreground hover:text-foreground">
                    <ArrowLeft className="mr-2 h-4 w-4" /> Back to Home
                </Button>
            </Link>

            <article className="prose prose-invert prose-lg max-w-none">
                <div className="mb-8 border-b border-border pb-8">
                    <div className="flex items-center gap-2 mb-4">
                        <span className="px-3 py-1 rounded-full text-sm font-medium bg-primary/20 text-primary border border-primary/20">
                            {effectivePost.category}
                        </span>
                        {!basePost?.content && (
                            <span className="flex items-center gap-1 text-xs uppercase tracking-widest text-primary">
                                <Sparkles size={14} /> AI generated
                            </span>
                        )}
                    </div>

                    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
                        <h1 className="text-5xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-foreground to-muted-foreground leading-tight">
                            {effectivePost.title}
                        </h1>
                    </div>

                    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between text-muted-foreground text-sm">
                        <div className="flex items-center gap-4 flex-wrap">
                            <div className="flex items-center gap-2">
                                <div className="w-8 h-8 rounded-full bg-gradient-to-br from-primary to-secondary flex items-center justify-center text-white font-bold">
                                    {effectivePost.author.charAt(0)}
                                </div>
                                {effectivePost.author}
                            </div>
                            <div className="flex items-center gap-2">
                                <Calendar size={16} />
                                {effectivePost.date}
                            </div>
                        </div>

                        {user && basePost && (
                            <div className="flex gap-2 flex-wrap">
                                <Link href={`/edit/${effectivePost.id}`}>
                                    <Button variant="outline" size="sm">
                                        <Edit size={14} className="mr-2" /> Edit
                                    </Button>
                                </Link>
                                <Button variant="destructive" size="sm" onClick={handleDelete}>
                                    <Trash2 size={14} className="mr-2" /> Delete
                                </Button>
                            </div>
                        )}
                    </div>
                </div>

                {resolvedContent ? (
                    <div className="space-y-4">
                        <div className="flex justify-end">
                            {speechSupported && (
                                <Button
                                    type="button"
                                    variant="outline"
                                    size="sm"
                                    className="gap-2"
                                    onClick={handleToggleListen}
                                >
                                    {isSpeaking ? <VolumeX size={16} /> : <Volume2 size={16} />}
                                    {isSpeaking ? 'Stop audio' : 'Listen to content'}
                                </Button>
                            )}
                        </div>
                        <div className="text-foreground leading-loose whitespace-pre-wrap">
                            {resolvedContent}
                        </div>
                    </div>
                ) : (
                    <div className="flex flex-col items-center gap-4 text-muted-foreground py-12">
                        <Loader2 className="h-8 w-8 animate-spin text-primary" />
                        <p>Crafting a fresh AI perspective…</p>
                    </div>
                )}

                {!basePost?.content && (
                    <div className="mt-8 flex flex-wrap gap-3">
                        <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            className="gap-2"
                            onClick={handleGenerateManually}
                            isLoading={aiGenerating}
                        >
                            <Sparkles size={14} />
                            Regenerate AI draft
                        </Button>
                    </div>
                )}
            </article>
        </motion.div>
    );
}
